### PR TITLE
test

### PR DESCRIPTION
**Pull request by LeoGrin**
### Change Description

*Try to be precise. You can additionally add comments to your PR, this might help the reviewer a lot.*

**If you used new dependencies: Did you add them to `requirements.txt`?**

**Who did you ping on Mattermost to review your PR? Please ping that person again whenever you are ready for another review.**

## Breaking changes

If you made any breaking changes, please update the version number.
Breaking changes are totally fine, we just need to make sure to keep the users informed and the server in sync.

**Does this PR break the API? If so, what is the corresponding server commit?**

**Does this PR break the user interface? If so, why?**

---
*Please do not mark comments/conversations as resolved unless you are the assigned reviewer. This helps maintain clarity during the review process.*

### CODE REVIEW

**Comment by LeoGrin** [comment]
This is a toy pr (no change) to check that the CI breaking is not due to some changes in another PR. Would some of you have an idea of what's causing the error? @SamuelGabriel @davidotte maybe?  Maybe something changed in the CI or something? I get no error when running the tests locally.

**Comment by davidotte** [comment]
No idea, I would also need to investigate :thinking:

**Comment by noahho** [comment]
Could it be the mock server tabpfn-server-wjedmz7r5a-ez.a.run.app has changed? The restx library seems to be stable for a while

**Comment by noahho** [comment]
Locally things are running, but not on the server

**Comment by LeoGrin** [comment]
Okay it seems to be due to version differences in the `httpx` package. Downgrading to `httpx-0.27.2` makes it work locally while the latest version (`0.28.1`) also fails locally. `0.28.1` came out on December 6th, and we don't specify the version in the `requirement.txt` file so the CI uses the latest version.

**Comment by LeoGrin** [comment]
#51 should fix this

**Pull request closed without merging**
