### PR TITLE
Fix:  Test Cases + enable Model Config for TabpfnClassifier after init based on use_server

### PR DESCRIPTION
**Pull request by anshulg954**
Issues: init did not had any use_server 
Fix: 2 alternatives : dont pass the variable, or add the argument to the func (I did the latter)

Modifications:
Enable Model Config and add support classifier paramets.

### CODE REVIEW

**Comment by SamuelGabriel** [comment]
Should this PR be reviewed?

- If it should be reviewed, make someone the reviewer by clicking on them in the top left and ping them on mattermost, like you did for your other PR (you can make this me or Liam ideally at this point)
- If it should not be reviewed, please label the PR as draft in the title "DRAFT Title"

**Comment by anshulg954** [comment]
Sure Sam! There's a case I need to discuss with Liam as mentioned in the meeting, I will assign the reviewer after that.

**Review by SamuelGabriel — APPROVED** [review]
This looks good. One minor thing: I know I told you the name "public_tabpfn", but I think "tabpfn_1" would be the better name for it. Could you change that plase?

**Comment by liam-sbhoo** [comment]
Look good to me. Ready to merge after renaming (as per Sam's request).

**Review by liam-sbhoo — APPROVED** [review]
Look good to me. Ready to merge after renaming (as per Sam's request).

**Comment by anshulg954** [comment]
Changed the name from public_tabpfn_local  to tabpfn_1_local.  

The two server based names are: tabpfn_1_local and latest_tabpfn_hosted.

**Pull request merged**
